modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="create-dimensions"
version="${file.jarVersion}"
displayName="Create: Dimensions"
logoFile="pack.png"
authors="JustRed23"
description='''
Create: Dimensions adds support for transportation of items, fluids, and rotational energy between dimensions.
'''

[[dependencies.create-dimensions]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create-dimensions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create-dimensions]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.c,)"
    ordering="NONE"
    side="BOTH"
